function [ Br,Bz,Bphi ] = finiteelementB(I,x1,y1,z1,x2,y2,z2,R_3D,Z_3D,phi_3D)
%UNTITLED4 此处显示有关此函数的摘要
%   calculate the magnetic induction at (r0,z0,phi0) generated by straight line current which flows from
%   (x1,y1,z1) to (x2,y2,z2) with the current value I. 
x0=R_3D.*cos(phi_3D);
y0=R_3D.*sin(phi_3D);
z0=Z_3D;

u0=10^(-7);
% u0=1;
% Xn(1,1)=x1;Yn(1,1)=y1;Zn(1,1)=z1;
% Xn(1,2)=x1;Yn(1,2)=y1;Zn(1,2)=z1;
% Xn=linspace(x1,x2,2);
% Yn=linspace(y1,y2,2);
% Zn=linspace(z1,z2,2);

% n=length(Xn)-1;
% [Bx,By,Bz]=deal(0);
% [Bn,Bnx,Bny,Bnz]=deal(zeros(1,n));


      X=(x1+x2)./2;
      Y=(y1+y2)./2;
      Z=(z1+z2)./2;
      dx=x2-x1;
      dy=y2-y1;
      dz=z2-z1;
      r=sqrt((X-x0).^2+(Y-y0).^2+(Z-z0).^2);
      Bx=(u0*I./(r.^3)).*((z0-Z).*dy-(y0-Y).*dz);
      By=(u0*I./(r.^3)).*((x0-X).*dz-(z0-Z).*dx);
      Bz=(u0*I./(r.^3)).*((y0-Y).*dx-(x0-X).*dy);

      

      Br=Bx.*cos(phi_3D)+By.*sin(phi_3D);
      Bphi=Bx.*sin(phi_3D)-By.*cos(phi_3D);
      Bz=Bz;
% 
% 
% Br=sqrt(Bx.^2+By.^2);
% Bphi=asin(complex(By./Br));
% Bz=Bz;

end
